# First Assignment

## First Assignment

### This weeks assignment is all about getting ourselves familiar with the jupyter notebook interface 

In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
A=np.array([2,3,4,5])

In [9]:
B=np.array([[4,6,8,9],[6,8,8,9]])


In [11]:
B


array([[4, 6, 8, 9],
       [6, 8, 8, 9]])

In [13]:
# This will show the array and the index it is located.
b=np.where(B==6)
b

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

# DATA TYPES

## List (mutable)

In [84]:
# Lists allow duplicates, as seen below
fruits = ["apple", "banana", "orange", "apple"]
digits = [1,2,3,4,5]

In [19]:
print(fruits)
print(digits)

['apple', 'banana', 'orange', 'apple']
[1, 2, 3, 4, 5]


In [21]:
print(fruits[0])
print(digits[3])

apple
4


In [23]:
print(len(fruits))
print(len(digits))

4
5


In [86]:
# List allows assignment.
fruits[0] = "grape"
fruits.append("mango") 
fruits

['grape', 'banana', 'orange', 'apple', 'mango']

In [27]:
fruits.remove("mango")
fruits

['apple', 'banana', 'orange', 'apple']

## Dictionary (mutable)

In [34]:
# Dict is used to store information in Key and value as seen in the example below.
student = {
    "name": "Aliu Qudus",
    "age": 20,
    "course": "Machine Learning"
}

print(student["name"]) 

Aliu Qudus


In [40]:
# Dictionary allows assignment and updates
student["course"] = "Machine Learning & AI"
student["age"] = 24
student["school"] = "M4ace"

In [42]:
student

{'name': 'Aliu Qudus',
 'age': 24,
 'course': 'Machine Learning & AI',
 'school': 'M4ace'}

In [46]:
student["school"]

'M4ace'

## Set (mutable)

In [70]:
# Sets don't allow duplicates, as seen in the output.
numbers = {1, 2, 3, 3, 4}

print(numbers)

{1, 2, 3, 4}


In [52]:
numbers.add(5)

In [54]:
numbers

{1, 2, 3, 4, 5}

In [72]:
# although sets might be mutable, they don't allow assignments
numbers[0] = 6

TypeError: 'set' object does not support item assignment

In [56]:
numbers.remove(2)

In [58]:
numbers

{1, 3, 4, 5}

## Tuple (not mutable)

In [74]:
# Tuple cannot be changed
scores = (90, 85, 90, 70)

print(scores)

(90, 85, 90, 70)


In [66]:
scores[0] = 100

TypeError: 'tuple' object does not support item assignment

In [78]:
scores.append(98)

AttributeError: 'tuple' object has no attribute 'append'

In [80]:
scores.add(98)

AttributeError: 'tuple' object has no attribute 'add'

In [90]:
scores

(90, 85, 90, 70)

# Simple calculator

In [112]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

operation = input("Choose operation (+, -, *, /): ")

if operation == "+":
    result = num1 + num2
elif operation == "-":
    result = num1 - num2
elif operation == "*":
    result = num1 * num2
elif operation == "/":
    if num2 != 0:
        result = num1 / num2
    else:
        result = "undefined"
else:
    result = "Invalid operation"

# Display result
print("Result:", result)

Enter first number:  25
Enter second number:  0
Choose operation (+, -, *, /):  /


Result: undefined


# Login System

In [133]:
users = {
    "Aliu": "Learning",
    "student": "learner",
    "Chi": "drinks"
}


while True:
    username = input("Enter your username: ")
    password = input("Enter your password: ")

    if username not in users:
        print("Username not found. Please try again.\n")
    elif users[username] != password:
        print("Password is incorrect. Please try again.\n")
    else:
        print("Login successful! Welcome,", username)
        break 



Enter your username:  Aliu
Enter your password:  Welcome


Password is incorrect. Please try again.



Enter your username:  Qudus
Enter your password:  Learning


Username not found. Please try again.



Enter your username:  Qud
Enter your password:  Wel


Username not found. Please try again.



Enter your username:  Aliu
Enter your password:  Learning


Login successful! Welcome, Aliu


# Declare all the data structure with varying samples

# List

In [31]:
# Lists allow duplicates, as seen below
fruits = ["apple", "banana", "orange", "apple"]
digits = [1,2,3,4,5]

In [33]:
digits.sort()
fruits.sort()

In [35]:
fruits

['apple', 'apple', 'banana', 'orange']

In [37]:
digits

[1, 2, 3, 4, 5]

In [39]:
print(fruits)
print(digits)

['apple', 'apple', 'banana', 'orange']
[1, 2, 3, 4, 5]


In [41]:
print(fruits[0])
print(digits[3])

apple
4


In [43]:
print(len(fruits))
print(len(digits))

4
5


In [45]:
# List allows assignment.
fruits[0] = "grape"
fruits.append("mango") 
fruits

['grape', 'apple', 'banana', 'orange', 'mango']

In [47]:
fruits.remove("mango")
fruits

['grape', 'apple', 'banana', 'orange']

# Dictionary

In [51]:
# Dict is used to store information in Key and value as seen in the example below.
student = {
    "name": "Aliu Qudus",
    "age": 20,
    "course": "Machine Learning"
}

print(student["name"]) 

Aliu Qudus


In [53]:
# Dictionary allows assignment and updates
student["course"] = "Machine Learning & AI"
student["age"] = 24
student["school"] = "M4ace"

In [55]:
student

{'name': 'Aliu Qudus',
 'age': 24,
 'course': 'Machine Learning & AI',
 'school': 'M4ace'}

In [57]:
student["school"]

'M4ace'

# Set

In [76]:
# Sets don't allow duplicates, as seen in the output.
numbers = {1, 2, 3, 3, 4,10}
digits = {4,5,6,5,2,2,7}

print(numbers)
print(digits)

{1, 2, 3, 4, 10}
{2, 4, 5, 6, 7}


In [68]:
numbers.add(5)
digits.add(3)
digits.pop()

2

In [70]:
digits

{3, 4, 5, 6, 7}

In [72]:
numbers

{1, 2, 3, 4, 5}

In [74]:
# although sets might be mutable, they don't allow assignments
numbers[0] = 6

TypeError: 'set' object does not support item assignment

In [78]:
numbers.remove(10)

In [80]:
numbers

{1, 2, 3, 4}

In [84]:
union = numbers.union(digits)
union

{1, 2, 3, 4, 5, 6, 7}

In [88]:
diff = numbers.difference(digits)
diff

{1, 3}

In [92]:
intersect = numbers.intersection(digits)
intersect

{2, 4}

# Tuple

In [95]:
# Tuple cannot be changed
scores = (90, 85, 90, 70)

print(scores)

(90, 85, 90, 70)


In [97]:
scores[0] = 100

TypeError: 'tuple' object does not support item assignment

In [99]:
scores.append(98)

AttributeError: 'tuple' object has no attribute 'append'

In [101]:
scores.add(98)

AttributeError: 'tuple' object has no attribute 'add'

In [103]:
scores

(90, 85, 90, 70)